"""Add base

Revision ID: a296d73399e1
Revises: 3aefacb7dc6c
Create Date: 2023-05-22 21:52:21.943237

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a296d73399e1'
down_revision = '3aefacb7dc6c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
